# Generated by Django 3.2.7 on 2026-03-08 06:54

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectTradeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Buyer Approval'), ('ACCEPTED', 'Accepted - QR Pending'), ('REJECTED', 'Rejected by Buyer'), ('CANCELLED', 'Cancelled by Farmer')], default='PENDING', max_length=20)),
                ('message', models.TextField(blank=True, help_text='Custom message to the buyer', null=True)),
                ('security_token', models.CharField(blank=True, help_text='Unique cryptographic token for QR', max_length=100, null=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='trade_qrs/')),
                ('is_paid', models.BooleanField(default=False, help_text='Has the escrow payment been released?')),
                ('scheduled_pickup_date', models.DateTimeField(blank=True, help_text="When the buyer's truck will arrive", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InputOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('quantity', models.FloatField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI Payment'), ('CARD', 'Credit/Debit Card'), ('COD', 'Cash on Delivery')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Order Placed & Pending'), ('SHIPPED', 'Shipped by Seller'), ('DELIVERED', 'Delivered successfully'), ('CANCELLED', 'Order Cancelled')], default='PENDING', max_length=20)),
                ('delivery_address', models.TextField(help_text='Snapshot of address at time of order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PincodeDirectory',
            fields=[
                ('pincode', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('FARMER', 'Farmer'), ('BUYER', 'Buyer'), ('SELLER', 'Seller'), ('ADMIN', 'Admin')], default='FARMER', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=50)),
                ('month', models.IntegerField()),
                ('avg_temp', models.FloatField()),
                ('avg_humidity', models.FloatField()),
                ('avg_rainfall', models.FloatField()),
            ],
            options={
                'unique_together': {('district', 'month')},
            },
        ),
        migrations.CreateModel(
            name='UnifiedReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='1 to 5 Stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('b2b_trade', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='Kultiva.directtradeproposal')),
                ('input_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='Kultiva.inputorder')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('sp_id', models.AutoField(primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wing', models.CharField(choices=[('PRODUCE', 'Farm Produce (Harvest)'), ('INPUT', 'Farming Input (Tools/Seeds/Fertilizers)')], max_length=15)),
                ('category', models.CharField(choices=[('GRAINS', 'Grains & Cereals'), ('VEGETABLES', 'Vegetables'), ('FRUITS', 'Fruits'), ('CASH_CROPS', 'Cash Crops (Cotton, Sugarcane)'), ('SPICES', 'Spices & Condiments'), ('SEEDS', 'Seeds'), ('FERTILIZERS', 'Fertilizers & Nutrients'), ('AGROCHEMICALS', 'Pesticides & Herbicides'), ('TOOLS', 'Farming Tools'), ('MACHINERY', 'Heavy Machinery & Parts')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('variety_or_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(help_text='Detailed description.')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_of_measure', models.CharField(max_length=20)),
                ('available_stock', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='market_images/')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active & In Stock'), ('OUT_OF_STOCK', 'Out of Stock'), ('HIDDEN', 'Hidden by Seller'), ('BANNED', 'Removed by Admin')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('min_order_quantity', models.FloatField(default=1, help_text='Minimum amount buyer must purchase')),
                ('harvest_date', models.DateField(blank=True, help_text='Required for Produce', null=True)),
                ('is_organic', models.BooleanField(default=False, help_text='Is this certified organic?')),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('listed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ManualSoilReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_status', models.CharField(choices=[('PENDING', 'Pending Lab Test'), ('COMPLETED', 'Test Completed / Data Uploaded')], default='PENDING', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('land_area', models.FloatField(blank=True, help_text='Area in Acres/Hectares', null=True)),
                ('previous_crop', models.CharField(blank=True, help_text='Crop harvested last season', max_length=100, null=True)),
                ('n', models.FloatField(blank=True, null=True)),
                ('p', models.FloatField(blank=True, null=True)),
                ('k', models.FloatField(blank=True, null=True)),
                ('ph', models.FloatField(blank=True, null=True)),
                ('farmer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manual_soil_report', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='inputorder',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inputorder',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Kultiva.marketplacelisting'),
        ),
        migrations.CreateModel(
            name='GridSoilData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_lat', models.FloatField(help_text='Latitude (2 decimals)')),
                ('grid_lon', models.FloatField(help_text='Longitude (2 decimals)')),
                ('ph', models.FloatField(help_text='pH level')),
                ('ec', models.FloatField(help_text='Electrical Conductivity')),
                ('oc', models.FloatField(help_text='Organic Carbon (%)')),
                ('avg_n', models.FloatField(help_text='Nitrogen (N)')),
                ('avg_p', models.FloatField(help_text='Phosphorus (P)')),
                ('avg_k', models.FloatField(help_text='Potassium (K)')),
                ('avg_s', models.FloatField(help_text='Sulphur (S)')),
                ('avg_zn', models.FloatField(help_text='Zinc (Zn)')),
                ('avg_fe', models.FloatField(help_text='Iron (Fe)')),
                ('avg_cu', models.FloatField(help_text='Copper (Cu)')),
                ('avg_mn', models.FloatField(help_text='Manganese (Mn)')),
                ('avg_b', models.FloatField(help_text='Boron (B)')),
                ('recommendation_text', models.TextField(blank=True, help_text='Rule-based SHC Advisory', null=True)),
            ],
            options={
                'unique_together': {('grid_lat', 'grid_lon')},
            },
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('fp_id', models.AutoField(primary_key=True, serialize=False)),
                ('aadhar_no', models.CharField(max_length=12, unique=True)),
                ('land_area', models.FloatField()),
                ('soil_type', models.CharField(max_length=20)),
                ('irrigation', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('ESCROW_LOCKED', 'Funds Locked in Escrow'), ('COMPLETED', 'Payment Released to Vendor'), ('REFUNDED', 'Payment Refunded')], default='COMPLETED', max_length=20)),
                ('security_token', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item_purchased', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Kultiva.marketplacelisting')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases_made', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='directtradeproposal',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directtradeproposal',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directtradeproposal',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_proposals', to='Kultiva.marketplacelisting'),
        ),
        migrations.CreateModel(
            name='BuyerProfile',
            fields=[
                ('bp_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('gst_number', models.CharField(max_length=15, unique=True)),
                ('iec_code', models.CharField(max_length=10)),
                ('apeda_org', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('addr_id', models.AutoField(primary_key=True, serialize=False)),
                ('village', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('pincode', models.CharField(max_length=6)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
