# Generated by Django 3.2.7 on 2026-03-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kultiva', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directtradeproposal',
            name='requested_quantity',
            field=models.FloatField(default=1.0, help_text='Amount the buyer actually wants to buy'),
        ),
    ]
