# Generated by Django 3.2.7 on 2026-03-20 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kultiva', '0002_directtradeproposal_requested_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='directtradeproposal',
            name='proposed_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Custom negotiated price per unit', max_digits=10),
        ),
        migrations.AddField(
            model_name='directtradeproposal',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total value of the negotiated deal', max_digits=12),
        ),
        migrations.AlterField(
            model_name='directtradeproposal',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Buyer Approval'), ('ACCEPTED', 'Accepted - QR Pending'), ('REJECTED', 'Rejected by Buyer'), ('CANCELLED', 'Cancelled by Farmer'), ('COMPLETED', 'Completed Trade')], default='PENDING', max_length=20),
        ),
    ]
