# Generated by Django 3.2.7 on 2026-03-24 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kultiva', '0003_auto_20260320_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualsoilreport',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_soil_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
