# Generated by Django 3.2.7 on 2026-03-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kultiva', '0004_alter_manualsoilreport_farmer'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualsoilreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='soil_reports/'),
        ),
    ]
