# Generated by Django 3.2.7 on 2026-03-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kultiva', '0005_manualsoilreport_report_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images/'),
        ),
    ]
