# Generated by Django 3.2.7 on 2026-04-01 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kultiva', '0006_unifiedreview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmerprofile',
            name='kissan_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
