# Generated by Django 3.2.7 on 2026-04-10 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Kultiva', '0007_auto_20260401_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manualsoilreport',
            name='land_area',
        ),
        migrations.AddField(
            model_name='manualsoilreport',
            name='farm_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_reports', to='Kultiva.address'),
        ),
    ]
